baseURL = 'https://kairos-foto-studio.github.io/'
languageCode = 'it-it'
title = 'Kairós | Fotografia'
theme = 'PaperMod'

[params]
    defaultTheme = 'dark'
    [params.homeInfoParams]
        Title = "Kairós"
        Content = "Museo privato di visioni digitali."
