baseURL = 'https://kairos-foto-studio.github.io/'
languageCode = 'it-it'
title = 'Kairós | Fotografia'
theme = 'github.com/adityatelange/hugo-PaperMod' # Link diretto

[params]
    defaultTheme = 'dark'
    [params.homeInfoParams]
        Title = "Kairós"
        Content = "Museo privato di visioni digitali."

[[params.socialIcons]]
    name = "foto"
    url = "images/kairos-start.png"
